redis:
  image: redis
  container_name: cache_db
  expose:
    - 6379
app:
  build: ./
  links:
    - redis
  container_name: webpf.net
  environment: 
    - REDIS_URL=cache_db
  ports: 
    - 9000:9000
    - 27017:27017
  expose:
    - 9000
    - 27017
  command:
    npm run start